FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the project files
WORKDIR /app
COPY . .

# Collect static files (if applicable)
RUN python manage.py collectstatic --noinput

# Expose port for Daphne
EXPOSE 8000

# Default command to run Daphne
CMD ["daphne", "-p", "8000", "kawaiiAPI.asgi:application"]
