FROM python:3.12-slim

# Set environment variable
ENV PYTHONDONOTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

# Install system dependencies
# RUN apt-get update && apt-get install -y \
#     postgresql libpq-dev gcc python3-dev musl-dev \
#     && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# Command to run the Django development server
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
