version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redis-main
    ports:
     - "6379:6379"

  app:
    build: .
    container_name: kawaiiapi
    volumes:
      - .:/app
    command: daphne -p 8000 -b 0.0.0.0 kawaiiAPI.asgi:application  # Run Daphne
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      DEBUG: "False"
      SECRET_KEY: "django-insecure-le41^5*zazcf%@9r2vmkip1%h#f)uba6osnt1_4-v2o9f$(bmb"
      REDIS_URL: "redis://redis:6379/0"

# No volumes for database are needed
