# Generated by Django 5.1.1 on 2024-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymongo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='billing_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
