# Generated by Django 5.1.1 on 2024-10-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymongo', '0002_webhookevent_billing_id_webhookevent_event_id'),
        ('transactions', '0021_payment_content_type_payment_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevent',
            name='billing_id',
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.billing'),
        ),
    ]
