# Generated by Django 5.0.7 on 2024-10-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=100)),
                ('rate_per_head', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AmenitiesAvailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_count', models.SmallIntegerField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.amenities')),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities_availed', to='transactions.billing')),
            ],
        ),
        migrations.CreateModel(
            name='AdditonalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_payment', to='transactions.billing')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesAvailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_availed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.activity')),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_availed', to='transactions.billing')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.billingstatus'),
        ),
        migrations.AddField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.customer'),
        ),
        migrations.CreateModel(
            name='FoodBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('or_number', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_bill', to='transactions.billing')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=100)),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.billing')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.gueststatus')),
            ],
        ),
    ]
