# Generated by Django 5.1.1 on 2024-10-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_payment_content_type_payment_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='amenitiesavailed',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities_availed', to='transactions.amenities'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='transactions.billing'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='transactions.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentFor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='transactions.paymentfor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='transactions.paymentstatus'),
        ),
    ]
