# Generated by Django 5.1.1 on 2024-10-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_extraitems_alter_amenitiesavailed_amenity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItemsAvailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='transactions.billing')),
                ('extraItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='transactions.extraitems')),
            ],
        ),
    ]
