# Generated by Django 5.1.1 on 2024-10-24 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='transactions.foodtype'),
            preserve_default=False,
        ),
    ]
