# Generated by Django 5.1.1 on 2024-10-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiesavailed',
            name='time',
            field=models.TimeField(blank=True, default='10:00', null=True),
        ),
    ]
