# Generated by Django 5.1.1 on 2024-10-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_alter_amenitiesavailed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additonalpayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
