# Generated by Django 5.1.1 on 2025-01-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0001_initial'),
        ('transactions', '0029_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiesavailed',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities_availed', to='offerings.amenities'),
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
