# Generated by Django 5.1.1 on 2025-01-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingstatus',
            old_name='status',
            new_name='name',
        ),
    ]
