# Generated by Django 5.1.1 on 2025-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_rename_status_billingstatus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingstatus',
            old_name='name',
            new_name='status',
        ),
    ]
