# Generated by Django 5.1.1 on 2025-01-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0002_activity'),
        ('transactions', '0030_alter_amenitiesavailed_amenity_delete_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesavailed',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offerings.activity'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
