# Generated by Django 4.2.30 on 2026-07-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_rename_name_billingstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Complete', 'Complete'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
        migrations.DeleteModel(
            name='BillingStatus',
        ),
    ]
