# Generated by Django 5.1.1 on 2025-01-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_alter_activitiesavailed_activity_delete_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
