# Generated by Django 5.1.1 on 2025-01-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0004_extraitems_amenitiesavailed'),
        ('transactions', '0032_delete_food_delete_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraitemsavailed',
            name='extraItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='offerings.extraitems'),
        ),
        migrations.DeleteModel(
            name='AmenitiesAvailed',
        ),
        migrations.DeleteModel(
            name='ExtraItems',
        ),
    ]
