# Generated by Django 6.0.7 on 2026-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_billing_status_to_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='status',
            field=models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Complete', 'Complete'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
        migrations.DeleteModel(
            name='GuestStatus',
        ),
    ]
