# Generated by Django 4.2.30 on 2026-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_alter_guestlist_status_alter_billing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentFor',
            field=models.CharField(blank=True, choices=[('Room', 'Room'), ('Down payment', 'Down payment'), ('Activities', 'Activities'), ('Amenities', 'Amenities'), ('Food', 'Food'), ('Additional', 'Additional')], max_length=20, null=True),
        ),
    ]
