# Generated by Django 5.1.1 on 2025-01-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_alter_extraitemsavailed_extraitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraitemsavailed',
            name='customer_bill',
        ),
        migrations.RemoveField(
            model_name='extraitemsavailed',
            name='extraItem',
        ),
        migrations.RemoveField(
            model_name='foodbill',
            name='customer_bill',
        ),
        migrations.DeleteModel(
            name='ActivitiesAvailed',
        ),
        migrations.DeleteModel(
            name='ExtraItemsAvailed',
        ),
        migrations.DeleteModel(
            name='FoodBill',
        ),
    ]
