# Generated by Django 6.0.7 on 2026-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_payment_for_fk_to_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Complete', 'Complete'), ('Booking Paid', 'Booking Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
