# Generated by Django 6.0.7 on 2026-08-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_alter_billing_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditonalPayment',
            new_name='AdditionalPayment',
        ),
    ]
