# Generated by Django 6.0.7 on 2026-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_billing_billing_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_reference',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
    ]
