# Generated by Django 6.0.7 on 2026-09-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_alter_billing_billing_reference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditonalPayment',
            new_name='AdditionalPayment',
        ),
    ]
