# Generated by Django 5.1.1 on 2025-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=100)),
                ('rate_per_head', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
