# Generated by Django 5.1.1 on 2025-01-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0003_foodtype_food'),
        ('transactions', '0032_delete_food_delete_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AmenitiesAvailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_count', models.SmallIntegerField()),
                ('time', models.TimeField(blank=True, default='10:00', null=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities_availed', to='offerings.amenities')),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities_availed', to='transactions.billing')),
            ],
        ),
    ]
