# Generated by Django 5.1.1 on 2025-01-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0004_extraitems_amenitiesavailed'),
        ('transactions', '0034_remove_extraitemsavailed_customer_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesAvailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_availed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offerings.activity')),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_availed', to='transactions.billing')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraItemsAvailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('customer_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='transactions.billing')),
                ('extraItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='offerings.extraitems')),
            ],
        ),
        migrations.CreateModel(
            name='FoodBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('or_number', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_bill', to='transactions.billing')),
            ],
        ),
    ]
