# Generated by Django 5.1.1 on 2025-01-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0005_activitiesavailed_extraitemsavailed_foodbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenitiesavailed',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='amenitiesavailed',
            name='customer_bill',
        ),
        migrations.RemoveField(
            model_name='extraitemsavailed',
            name='customer_bill',
        ),
        migrations.RemoveField(
            model_name='extraitemsavailed',
            name='extraItem',
        ),
        migrations.RemoveField(
            model_name='foodbill',
            name='customer_bill',
        ),
        migrations.DeleteModel(
            name='ActivitiesAvailed',
        ),
        migrations.DeleteModel(
            name='AmenitiesAvailed',
        ),
        migrations.DeleteModel(
            name='ExtraItemsAvailed',
        ),
        migrations.DeleteModel(
            name='FoodBill',
        ),
    ]
