# Generated by Django 5.1.1 on 2024-10-25 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_room_status_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.bookingstatus'),
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
