# Generated by Django 5.1.1 on 2024-10-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status_alter_bookingstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_guest',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
