# Generated by Django 5.1.1 on 2024-10-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_extra_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extra_guest',
        ),
    ]
