# Generated by Django 5.1.1 on 2024-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_extra_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extra_guest',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
