# Generated by Django 5.1.1 on 2025-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_booking_extra_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingstatus',
            old_name='name',
            new_name='status',
        ),
    ]
