# Generated by Django 6.0.7 on 2026-09-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_booking_status_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='max_adult',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='max_children',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_exta_guest',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='good_for',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
