# Generated by Django 6.0.7 on 2026-09-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_remove_roomtype_max_adult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='max_exta_guest',
            new_name='max_extra_guest',
        ),
    ]
