# Generated by Django 6.0.7 on 2026-09-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_rename_max_exta_guest_roomtype_max_extra_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
