# Generated by Django 6.0.7 on 2026-09-16 06:49

from django.db import migrations
import random

def generate_booking_ref():
    allowed_chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
    return ''.join(random.choices(allowed_chars, k=6))


def populate_booking_references(apps, schema_editor):
    # Fetch the model history securely via the apps registry
    Booking = apps.get_model('bookings', 'Booking') # <-- CHANGE 'your_app_name' HERE
    
    # Loop through only the rows that don't have a code yet
    for booking in Booking.objects.filter(reference_id__isnull=True):
        code = generate_booking_ref()
        # Ensure it doesn't conflict with any newly generated codes in this loop
        while Booking.objects.filter(reference_id=code).exists():
            code = generate_booking_ref()
        
        booking.reference_id = code
        booking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_reference_id'),
    ]

    operations = [
        migrations.RunPython(populate_booking_references),
    ]
