# Generated by Django 6.0.7 on 2026-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20260916_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_id',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
