# Generated by Django 6.0.7 on 2026-09-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_alter_booking_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reference_id',
        ),
    ]
